filebeat.inputs:
  - type: filestream
    id: app-logs
    enabled: true
    paths:
      - /logs/eureka/*.log
      - /logs/gateway/*.log
      - /logs/product/*.log
      - /logs/order/*.log

    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true

    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

      - rename:
          fields:
            - from: "service"
              to: "service_name"
          ignore_missing: true
          fail_on_error: false

    fields:
      environment: "dev"
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"