spring.application.name=product-service
server.port=8081

# =============================================
# MongoDB
# =============================================
spring.data.mongodb.uri=mongodb://localhost:27017/ProductDb

# =============================================
# Eureka Client
# =============================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# =============================================
# Actuator
# =============================================
management.endpoints.web.exposure.include=*

logging.level.com.poc.product=DEBUG

logging.file.name=./logs/product/app.log
management.tracing.sampling.probability=1.0
management.tracing.export.enabled=false
management.tracing.enabled=true
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans